server:
  port: 9005
dubbo:
  scan:
    basePackages: com.jt
  application:
    name: consumer-user
  registry:
    address: zookeeper://192.168.48.129:2181?backup=192.168.48.129:2182,192.168.48.129:2183